saveExact: true
engineStrict: true
minimumReleaseAge: 1440
trustPolicy: "no-downgrade"
trustPolicyExclude:
  - effect@4.0.0-beta.70
  - semver@5.7.2 || 6.3.1
  - "@effect/platform-node-shared@4.0.0-beta.70"
allowBuilds:
  "@prisma/engines": true
  msgpackr-extract: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@better-auth/core@1.7.0'
  - '@better-auth/drizzle-adapter@1.7.0'
  - '@better-auth/kysely-adapter@1.7.0'
  - '@better-auth/memory-adapter@1.7.0'
  - '@better-auth/mongo-adapter@1.7.0'
  - '@better-auth/prisma-adapter@1.7.0'
  - '@better-auth/telemetry@1.7.0'
  - better-auth@1.7.0
